{
	"version": 1635732911,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/player-sheet0.png",
		"images/player-sheet1.png",
		"images/enemy1-sheet0.png",
		"images/enemy1-sheet1.png",
		"images/enemybullet-sheet0.png",
		"images/bullet-sheet0.png",
		"images/camera-sheet0.png",
		"images/wall-sheet0.png",
		"images/enemyhealthbar-sheet0.png",
		"images/win-sheet0.png",
		"images/whiteout-sheet0.png",
		"images/enemyparticles.png",
		"images/particles.png",
		"media/hurt.m4a",
		"media/hurt.ogg",
		"media/hit.m4a",
		"media/hit.ogg",
		"media/shoot3.m4a",
		"media/shoot3.ogg",
		"media/phasechange.m4a",
		"media/phasechange.ogg",
		"media/enemyroar.m4a",
		"media/enemyroar.ogg",
		"media/sevish - gleam (22-tone microtonal 5_4 beat).m4a",
		"media/sevish - gleam (22-tone microtonal 5_4 beat).ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}